export const WORD_REPOSITORY = Symbol('WORD_REPOSITORY');
export const GAME_SESSION_REPOSITORY = Symbol('GAME_SESSION_REPOSITORY');
export const LEADERBOARD_REPOSITORY = Symbol('LEADERBOARD_REPOSITORY');